FROM node:dubnium-jessie as builder

WORKDIR "/app"

COPY package.json .
RUN npm install
COPY . .

CMD ["npm", "run", "dev"]

FROM nginx
EXPOSE 2000
COPY /nginx/nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /app/build /usr/share/nginx/html