const mongoose = require("mongoose");
const ObjectId = mongoose.Types.ObjectId;
const Schema = mongoose.Schema;
const dbManager = require("../config/db");
const appDb = dbManager.getConnections()[0];
const Profile = require("../db/model/dating/profile")(appDb);

let profile = [
  {
    _id: new ObjectId(),
    bio: "hi....",
    name: "Minh Thu",
    avatars: [
      "https://192.168.100.9:2000/assets/images/MinhThu/minhthu1.jpg",
      "https://192.168.100.9:2000/assets/images/MinhThu/minhthu2.jpg",
      "https://192.168.100.9:2000/assets/images/MinhThu/minhthu3.jpg",
      "https://192.168.100.9:2000/assets/images/MinhThu/minhthu4.jpg",
    ],
    birthday: 1998 - 07 - 07,
    location: {},
    gender: "FEMALE",
    target: "CHATTING",
    height: 158,
    hometown: {},
    job: "Student",
    secondarySchool: "THPT Nhân Chính",
    university: "Học viện tài chính",
    educationLevel: "BACHELORS DEGREE",
    yourKids: "I DON'T HAVE KIDS",
    smoking: "NEVER",
    drinking: "OCCASIONALLY",
    religion: "PREFER NOT TO SAY",
    popularity: 20,
    filterSetting: {
      distance: 30,
      gender: "MALE",
      ageRange: { fromNumber: 18, toNumber: 30 },
      heightRange: { fromNumber: 149, toNumber: 180 },
      educationLevel: "NO PREFERENCE",
      theirKids: "THEY DON'T HAVE KIDS",
      religion: "NO PREFERENCE",
    },
    seen: [],
    root_user: new ObjectId(),
  },

  {
    _id: new ObjectId(),
    bio: "người ta thay bồ như thay áo, còn tôi quyết định không mặc gì",
    name: "Linh Đàm",
    avatars: [
      "https://192.168.100.9:2000/assets/images/LinhDam/linhdam1.jpg",
      "https://192.168.100.9:2000/assets/images/LinhDam/linhdam2.jpg",
      "https://192.168.100.9:2000/assets/images/LinhDam/linhdam3.jpg",
      "https://192.168.100.9:2000/assets/images/LinhDam/linhdam4.jpg",
      "https://192.168.100.9:2000/assets/images/LinhDam/linhdam5.jpg",
    ],
    birthday: 1998 - 07 - 07,
    location: {},
    gender: "FEMALE",
    target: "FRIENDSHIP",
    height: 160,
    hometown: {},
    job: "Streamer",
    secondarySchool: "",
    university: "",
    educationLevel: "PREFER NOT TO SAY",
    yourKids: "I DON'T HAVE KIDS",
    smoking: "OCCASIONALLY",
    drinking: "OCCASIONALLY",
    religion: "PREFER NOT TO SAY",
    popularity: 25,
    filterSetting: {
      distance: 6,
      gender: "MALE",
      ageRange: { fromNumber: 25, toNumber: 35 },
      heightRange: { fromNumber: 149, toNumber: 190 },
      educationLevel: "NO PREFERENCE",
      theirKids: "THEY DON'T HAVE KIDS",
      religion: "NO PREFERENCE",
    },
    seen: [],
    root_user: new ObjectId(),
  },

  {
    _id: new ObjectId(),
    bio: "Match để biết thêm chi tiết",
    name: "Lê Ngọc",
    avatars: [
      "https://192.168.100.9:2000/assets/images/LeNgoc/lengoc1.jpg",
      "https://192.168.100.9:2000/assets/images/LeNgoc/lengoc2.jpg",
      "https://192.168.100.9:2000/assets/images/LeNgoc/lengoc3.jpg",
      "https://192.168.100.9:2000/assets/images/LeNgoc/lengoc4.jpg",
      "https://192.168.100.9:2000/assets/images/LeNgoc/lengoc5.jpg",
      "https://192.168.100.9:2000/assets/images/LeNgoc/lengoc6.jpg",
    ],
    birthday: 1997 - 09 - 09,
    location: {},
    gender: "FEMALE",
    target: "LONG-TERM RELATIONSHIP",
    height: 170,
    hometown: {},
    job: "Nhân viên ngân hàng",
    secondarySchool: "THPT Hậu Lộc 2",
    university: "Học viện tài chính",
    educationLevel: "BACHELORS DEGREE",
    yourKids: "I DON'T HAVE KIDS",
    smoking: "NEVER",
    drinking: "OCCASIONALLY",
    religion: "PREFER NOT TO SAY",
    popularity: 22,
    filterSetting: {
      distance: 20,
      gender: "MALE",
      ageRange: { fromNumber: 24, toNumber: 30 },
      heightRange: { fromNumber: 170, toNumber: 200 },
      educationLevel: "",
      theirKids: "THEY DON'T HAVE KIDS",
      religion: "NO PREFERENCE",
    },
    seen: [],
    root_user: new ObjectId(),
  },

  {
    _id: new ObjectId(),
    bio: "Tìm một mối quan hệ nghiêm túc",
    name: "PhAnh",
    avatars: [
      "https://192.168.100.9:2000/assets/images/PhAnh/phanh1.jpg",
      "https://192.168.100.9:2000/assets/images/PhAnh/phanh2.jpg",
      "https://192.168.100.9:2000/assets/images/PhAnh/phanh3.jpg",
      "https://192.168.100.9:2000/assets/images/PhAnh/phanh4.jpg",
      "https://192.168.100.9:2000/assets/images/PhAnh/phanh5.jpg",
    ],
    birthday: 1998 - 07 - 16,
    location: {},
    gender: "FEMALE",
    target: "LONG-TERM RELATIONSHIP",
    height: 158,
    hometown: {},
    job: "",
    secondarySchool: "THPT Vạn Xuân",
    university: "Đại học Thăng Long",
    educationLevel: "BACHELORS DEGREE",
    yourKids: "I DON'T HAVE KIDS",
    smoking: "NEVER",
    drinking: "OCCASIONALLY",
    religion: "OTHER",
    popularity: 20,
    filterSetting: {
      distance: 18,
      gender: "MALE",
      ageRange: { fromNumber: 24, toNumber: 30 },
      heightRange: { fromNumber: 160, toNumber: 200 },
      educationLevel: "",
      theirKids: "THEY DON'T HAVE KIDS",
      religion: "NO PREFERENCE",
    },
    seen: [],
    root_user: new ObjectId(),
  },

  {
    _id: new ObjectId(),
    bio: "Tìm một người bạn nói chuyện những lúc buồn",
    name: "Quỳnh Anh",
    avatars: [
      "https://192.168.100.9:2000/assets/images/QuynhAnh/quynhanh1.jpg",
      "https://192.168.100.9:2000/assets/images/QuynhAnh/quynhanh2.jpg",
      "https://192.168.100.9:2000/assets/images/QuynhAnh/quynhanh3.jpg",
    ],
    birthday: 1996 - 02 - 12,
    location: {},
    gender: "FEMALE",
    target: "CHATTING",
    height: 168,
    hometown: {},
    job: "Youtuber",
    secondarySchool: "THPT Phan Đình Phùng",
    university: "Đại học FPT",
    educationLevel: "BACHELORS DEGREE",
    yourKids: "I DON'T HAVE KIDS",
    smoking: "NEVER",
    drinking: "OCCASIONALLY",
    religion: "OTHER",
    popularity: 30,
    filterSetting: {
      distance: 15,
      gender: "MALE",
      ageRange: { fromNumber: 26, toNumber: 30 },
      heightRange: { fromNumber: 170, toNumber: 200 },
      educationLevel: "BACHELORS DEGREE",
      theirKids: "THEY HAVE KIDS",
      religion: "NO PREFERENCE",
    },
    seen: [],
    root_user: new ObjectId(),
  },

  {
    _id: new ObjectId(),
    bio: "Đang lạc người anh yêu..",
    name: "Thủy Tiên",
    avatars: [
      "https://192.168.100.9:2000/assets/images/ThuyTien/thuytien1.jpg",
      "https://192.168.100.9:2000/assets/images/ThuyTien/thuytien2.jpg",
      "https://192.168.100.9:2000/assets/images/ThuyTien/thuytien3.jpg",
    ],
    birthday: 1996 - 10 - 22,
    location: {},
    gender: "FEMALE",
    target: "SOMETHING CASUAL",
    height: 163,
    hometown: {},
    job: "Streamer",
    secondarySchool: "Marie Curie HaNoi School",
    university: "Học viện ngân hàng",
    educationLevel: "BACHELORS DEGREE",
    yourKids: "I DON'T HAVE KIDS",
    smoking: "OCCASIONALLY",
    drinking: "OFTEN",
    religion: "HINDU",
    popularity: 28,
    filterSetting: {
      distance: 20,
      gender: "MALE",
      ageRange: { fromNumber: 26, toNumber: 30 },
      heightRange: { fromNumber: 170, toNumber: 200 },
      educationLevel: "NO PREFERENCE",
      theirKids: "THEY HAVE KIDS",
      religion: "NO PREFERENCE",
    },
    seen: [],
    root_user: new ObjectId(),
  },

  {
    _id: new ObjectId(),
    bio: "Thích thì ib",
    name: "Mỹ Hằng",
    avatars: [
      "https://192.168.100.9:2000/assets/images/MyHang/myhang1.jpg",
      "https://192.168.100.9:2000/assets/images/MyHang/myhang2.jpg",
      "https://192.168.100.9:2000/assets/images/MyHang/myhang3.jpg",
    ],
    birthday: 2000 - 10 - 16,
    location: {},
    gender: "FEMALE",
    target: "CHATTING",
    height: 164,
    hometown: {},
    job: "Makeup artist",
    secondarySchool: "THPT Duy Tân",
    university: "",
    educationLevel: "A-LEVELS,HIGHERS OR EQUIVALENT",
    yourKids: "I HAVE KIDS",
    smoking: "NEVER",
    drinking: "OCCASIONALLY",
    religion: "OTHER",
    popularity: 15,
    filterSetting: {
      distance: 20,
      gender: "MALE",
      ageRange: { fromNumber: 22, toNumber: 27 },
      heightRange: { fromNumber: 170, toNumber: 190 },
      educationLevel: "NO PREFERENCE",
      theirKids: "NO PREFERENCE",
      religion: "NO PREFERENCE",
    },
    seen: [],
    root_user: new ObjectId(),
  },

  {
    _id: new ObjectId(),
    bio:
      "Gửi tớ một lời chào, rồi tớ sẽ chào lại cậu bằng một lời thân ái. Một chiếc bạn xinh xắn nếu cậu muốn nói chuyện tếu táo để quên đi vài câu chuyện không vui hàng ngày..Indie, đồng âm, tarot, countrystlye, cat,dog....",
    name: "Mỹ Anh",
    avatars: [
      "https://192.168.100.9:2000/assets/images/MyAnh/myanh1.jpg",
      "https://192.168.100.9:2000/assets/images/MyAnh/myanh2.jpg",
      "https://192.168.100.9:2000/assets/images/MyAnh/myanh3.jpg",
    ],
    birthday: 1999 - 8 - 16,
    location: {},
    gender: "FEMALE",
    target: "CHATTING",
    height: 162,
    hometown: {},
    job: "Student",
    secondarySchool: "THPT Hậu Lộc 3",
    university: "Đại học Kinh tế quốc dân",
    educationLevel: "A-LEVELS,HIGHERS OR EQUIVALENT",
    yourKids: "I DON'T HAVE KIDS",
    smoking: "PREFER NOT TO SAY",
    drinking: "OCCASIONALLY",
    religion: "OTHER",
    popularity: 19,
    filterSetting: {
      distance: 3,
      gender: "MALE",
      ageRange: { fromNumber: 22, toNumber: 30 },
      heightRange: { fromNumber: 160, toNumber: 190 },
      educationLevel: "NO PREFERENCE",
      theirKids: "THEY DON'T HAVE KIDS",
      religion: "NO PREFERENCE",
    },
    seen: [],
    root_user: new ObjectId(),
  },

  {
    _id: new ObjectId(),
    bio: "Nếu match nghĩa là anh đẹp trai",
    name: "Khánh Linh",
    avatars: [
      "https://192.168.100.9:2000/assets/images/KhanhLinh/khanhlinh1.jpg",
      "https://192.168.100.9:2000/assets/images/KhanhLinh/khanhlinh2.jpg",
    ],
    birthday: 2001 - 8 - 16,
    location: {},
    gender: "FEMALE",
    target: "CHATTING",
    height: 175,
    hometown: {},
    job: "Student",
    secondarySchool: "THPT Trung Văn",
    university: "Đại học Bách khoa Hà Nội",
    educationLevel: "A-LEVELS,HIGHERS OR EQUIVALENT",
    yourKids: "I DON'T HAVE KIDS",
    smoking: "PREFER NOT TO SAY",
    drinking: "OCCASIONALLY",
    religion: "OTHER",
    popularity: 10,
    filterSetting: {
      distance: 15,
      gender: "MALE",
      ageRange: { fromNumber: 22, toNumber: 30 },
      heightRange: { fromNumber: 160, toNumber: 190 },
      educationLevel: "NO PREFERENCE",
      theirKids: "THEY DON'T HAVE KIDS",
      religion: "NO PREFERENCE",
    },
    seen: [],
    root_user: new ObjectId(),
  },

  {
    _id: new ObjectId(),
    bio: "Thích thì match, không thích thì match",
    name: "Diana Trần",
    avatars: [
      "https://192.168.100.9:2000/assets/images/DianaTran/dianatran1.jpg",
      "https://192.168.100.9:2000/assets/images/DianaTran/dianatran2.jpg",
      "https://192.168.100.9:2000/assets/images/DianaTran/dianatran3.jpg",
    ],
    birthday: 2000 - 3 - 1,
    location: {},
    gender: "FEMALE",
    target: "SOMETHING CASUAL",
    height: 155,
    hometown: {},
    job: "Student",
    secondarySchool: "THPT Đại Mỗ",
    university: "Đại học Xây dựng",
    educationLevel: "A-LEVELS,HIGHERS OR EQUIVALENT",
    yourKids: "I DON'T HAVE KIDS",
    smoking: "PREFER NOT TO SAY",
    drinking: "NEVER",
    religion: "OTHER",
    popularity: 10,
    filterSetting: {
      distance: 30,
      gender: "MALE",
      ageRange: { fromNumber: 24, toNumber: 30 },
      heightRange: { fromNumber: 170, toNumber: 190 },
      educationLevel: "NO PREFERENCE",
      theirKids: "THEY DON'T HAVE KIDS",
      religion: "NO PREFERENCE",
    },
    seen: [],
    root_user: new ObjectId(),
  },

  {
    _id: new ObjectId(),
    bio: "Thích thì match, không thích thì match",
    name: "Diana Trần",
    avatars: [
      "https://192.168.100.9:2000/assets/images/DianaTran/dianatran1.jpg",
      "https://192.168.100.9:2000/assets/images/DianaTran/dianatran2.jpg",
      "https://192.168.100.9:2000/assets/images/DianaTran/dianatran3.jpg",
    ],
    birthday: 2000 - 3 - 1,
    location: {},
    gender: "FEMALE",
    target: "SOMETHING CASUAL",
    height: 155,
    hometown: {},
    job: "Student",
    secondarySchool: "THPT Đại Mỗ",
    university: "Đại học Xây dựng",
    educationLevel: "A-LEVELS,HIGHERS OR EQUIVALENT",
    yourKids: "I DON'T HAVE KIDS",
    smoking: "PREFER NOT TO SAY",
    drinking: "NEVER",
    religion: "OTHER",
    popularity: 10,
    filterSetting: {
      distance: 30,
      gender: "MALE",
      ageRange: { fromNumber: 24, toNumber: 30 },
      heightRange: { fromNumber: 170, toNumber: 190 },
      educationLevel: "NO PREFERENCE",
      theirKids: "THEY DON'T HAVE KIDS",
      religion: "NO PREFERENCE",
    },
    seen: [],
    root_user: new ObjectId(),
  },
];
